import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import { Button, Layout } from 'antd';
import { Header } from '@/src/components/Header';
import '../styles/index.css';
import StyledComponentsRegistry from '../lib/AntdRegistry';
import Footer from '../components/Footer';

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <Layout>
            <Header />
            {children}
            <Footer />
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
